@baseUrl = http://localhost:3002

@jwtToken = {{authLogin.response.body.accessToken}} 


### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "leo@email.com",
    "password": "123456"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/123
Authorization: Bearer {{jwtToken}}

### create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "Leo",
    "email": "leo@email.com",
    "password": "123456"
}

### update user
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Leo",
    "email": "leo@email.com"
}

### update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "currentPassword": "123456",
    "newPassword": "123456"
}