@baseUrl = http://localhost:3002

@jwtToken = {{authLogin.response.body.accessToken}}

@postUuid = {{createPostOwned.response.body.id}}
@postSlug = {{createPostOwned.response.body.slug}}
@imagePath = {{uploadImage.response.body.url}}
@imageUrl = {{baseUrl}}{{imagePath}}

@userNameForTesting = Leo
@userEmailForTesting = leo@email.com
@userPasswordForTesting = 123456
@userNewPasswordForTesting = 12345

# Auth ####################################################

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "{{userEmailForTesting}}",
    "password": "{{userPasswordForTesting}}"
}

# User ####################################################

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/123
Authorization: Bearer {{jwtToken}}

### create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "{{userNameForTesting}}",
    "email": "{{userEmailForTesting}}",
    "password": "{{userPasswordForTesting}}"
}

### update user
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Leo",
    "email": "leo@email.com"
}

### update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "currentPassword": "123456",
    "newPassword": "123456"
}

### read one user
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

### delete one user
# @name deleteUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

# Post ####################################################

### create post owned
# @name createPostOwned
POST {{baseUrl}}/post/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "title": "Titulo do post",
    "excerpt": "excerto do post",
    "content": "conteudo"
}

